mqtt:
  sensor:
    #OpenWeatherMap
    - name: OpenWeatherMap Current Icon
      state_topic: openweathermap
      value_template: "{{value_json['current'].icon }}"
    - name: OpenWeatherMap Current Summary
      state_topic: openweathermap
      value_template: "{{value_json['current'].summary }}"
    - name: OpenWeatherMap Current Temperature
      state_topic: openweathermap
      value_template: "{{value_json['current'].temperature }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Current Visibility
      state_topic: openweathermap
      value_template: "{{value_json['current'].visibility }}"
      unit_of_measurement: "mi"
    - name: OpenWeatherMap Current Maximum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['current'].maxtemp }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Current Minimum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['current'].mintemp }}"
      unit_of_measurement: "°F"  
    - name: OpenWeatherMap Current Wind Bearing
      state_topic: openweathermap
      value_template: "{{value_json['current'].wind_dir }}"
      unit_of_measurement: "°"
    - name: OpenWeatherMap Current Wind Speed
      state_topic: openweathermap
      value_template: "{{value_json['current'].wind_spd }}"
      unit_of_measurement: "mi/h"
    - name: OpenWeatherMap Current Wind Gust
      state_topic: openweathermap
      value_template: "{{value_json['current'].wind_gust }}"
      unit_of_measurement: "mi/h"
    - name: OpenWeatherMap Current Humidity
      state_topic: openweathermap
      value_template: "{{value_json['current'].humidity }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Current Pressure
      state_topic: openweathermap
      value_template: "{{value_json['current'].pressure }}"
      unit_of_measurement: "hPa"
    - name: OpenWeatherMap Current Apparent Temperature
      state_topic: openweathermap
      value_template: "{{value_json['current'].apparent }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Current POP
      state_topic: openweathermap
      value_template: "{{value_json['current'].precip_chance }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Current Precip Forecast
      state_topic: openweathermap
      value_template: "{{value_json['current'].precip_forecast }}"
      unit_of_measurement: "in"
    - name: OpenWeatherMap Current UV Index
      state_topic: openweathermap
      value_template: "{{value_json['current'].uv_index }}"
    - name: OpenWeatherMap Current UV Risk
      state_topic: openweathermap
      value_template: "{{value_json['current'].uv_risk }}"
    - name: OpenWeatherMap Current UV Combined
      state_topic: openweathermap
      value_template: "{{value_json['current'].uv_combined }}"
    - name: OpenWeatherMap Day 1 Icon
      state_topic: openweathermap
      value_template: "{{value_json['day_1'].icon }}"
    - name: OpenWeatherMap Day 1 Summary
      state_topic: openweathermap
      value_template: "{{value_json['day_1'].summary }}"
    - name: OpenWeatherMap Day 1 Maximum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_1'].maxtemp }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Day 1 Minimum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_1'].mintemp }}"
      unit_of_measurement: "°F"  
    - name: OpenWeatherMap Day 1 POP
      state_topic: openweathermap
      value_template: "{{value_json['day_1'].precip_chance }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Day 1 Precip Forecast
      state_topic: openweathermap
      value_template: "{{value_json['day_1'].precip_forecast }}"
      unit_of_measurement: "in"
    - name: OpenWeatherMap Day 2 Icon
      state_topic: openweathermap
      value_template: "{{value_json['day_2'].icon }}"
    - name: OpenWeatherMap Day 2 Summary
      state_topic: openweathermap
      value_template: "{{value_json['day_2'].summary }}"
    - name: OpenWeatherMap Day 2 Maximum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_2'].maxtemp }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Day 2 Minimum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_2'].mintemp }}"
      unit_of_measurement: "°F"  
    - name: OpenWeatherMap Day 2 POP
      state_topic: openweathermap
      value_template: "{{value_json['day_2'].precip_chance }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Day 2 Precip Forecast
      state_topic: openweathermap
      value_template: "{{value_json['day_2'].precip_forecast }}"
      unit_of_measurement: "in"
    - name: OpenWeatherMap Day 3 Icon
      state_topic: openweathermap
      value_template: "{{value_json['day_3'].icon }}"
    - name: OpenWeatherMap Day 3 Summary
      state_topic: openweathermap
      value_template: "{{value_json['day_3'].summary }}"
    - name: OpenWeatherMap Day 3 Maximum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_3'].maxtemp }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Day 3 Minimum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_3'].mintemp }}"
      unit_of_measurement: "°F"  
    - name: OpenWeatherMap Day 3 POP
      state_topic: openweathermap
      value_template: "{{value_json['day_3'].precip_chance }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Day 3 Precip Forecast
      state_topic: openweathermap
      value_template: "{{value_json['day_3'].precip_forecast }}"
      unit_of_measurement: "in"
    - name: OpenWeatherMap Day 4 Icon
      state_topic: openweathermap
      value_template: "{{value_json['day_4'].icon }}"
    - name: OpenWeatherMap Day 4 Summary
      state_topic: openweathermap
      value_template: "{{value_json['day_4'].summary }}"
    - name: OpenWeatherMap Day 4 Maximum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_4'].maxtemp }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Day 4 Minimum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_4'].mintemp }}"
      unit_of_measurement: "°F"  
    - name: OpenWeatherMap Day 4 POP
      state_topic: openweathermap
      value_template: "{{value_json['day_4'].precip_chance }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Day 4 Precip Forecast
      state_topic: openweathermap
      value_template: "{{value_json['day_4'].precip_forecast }}"
      unit_of_measurement: "in"
    - name: OpenWeatherMap Day 5 Icon
      state_topic: openweathermap
      value_template: "{{value_json['day_5'].icon }}"
    - name: OpenWeatherMap Day 5 Summary
      state_topic: openweathermap
      value_template: "{{value_json['day_5'].summary }}"
    - name: OpenWeatherMap Day 5 Maximum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_5'].maxtemp }}"
      unit_of_measurement: "°F"
    - name: OpenWeatherMap Day 5 Minimum Temperature
      state_topic: openweathermap
      value_template: "{{value_json['day_5'].mintemp }}"
      unit_of_measurement: "°F"  
    - name: OpenWeatherMap Day 5 POP
      state_topic: openweathermap
      value_template: "{{value_json['day_5'].precip_chance }}"
      unit_of_measurement: "%"
    - name: OpenWeatherMap Day 5 Precip Forecast
      state_topic: openweathermap
      value_template: "{{value_json['day_5'].precip_forecast }}"
      unit_of_measurement: "in"
    - name: OpenWeatherMap Weekly Summary
      state_topic: openweathermap
      value_template: "{{value_json['alert_summary'] }}"
    - name: KCLL Current Visibility
      state_topic: weather/kcll/visibility
      unit_of_measurement: "mi"

sensor:
  - platform: template
    sensors:
      local_apparent_temperature:
        value_template: >-
          {% set temp = (states('sensor.acurite_outside_temperature') | float(0) - 32) * (5/9) %}
          {% set ws = states('sensor.openweathermap_current_wind_speed') | float(0) / 2.237 %}
          {% set p = (states('sensor.acurite_outside_humidity') | float(0) / 100) * 6.105 * e**((17.27 * temp) / (237.7 + temp)) %}
          {% set atc = temp + (0.33 * p) - (0.70 * ws) - 4 %}
          {% set at = (atc * (9/5)) + 32 %}
          {{ at | round(2,none) }}
        unit_of_measurement: "°F"
        device_class: temperature