title: The Geek House

# Preload Cards
preload_cards:
  - picture-elements

#################################################################
#                                                               #
#                    Compact Header Config                      #
#                                                               #
################################################################# 

custom_header:
  background: 'rgba(150, 150, 150, 0.2)'
  compact_mode: true
  hide_config: true
  hide_unused: true
  hide_help: true
  button_text:
    options: '{{ time }}<br>{{ date }}'
  default_tab: '0'

#############################################################################################################################################
#                                                                                                                                           # 
#                                                                BEGIN VIEWS                                                                #
#                                                                                                                                           #
#############################################################################################################################################  
 
background: center / cover no-repeat url("/local/lovelace/background_19.png") fixed
views: 
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/system.yaml