- alias: HVAC Night
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: disarmed
    to: armed_night
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_home
    to: armed_night
  action:
  - service: climate.home
    data:
      entity_id: climate.master_suite
      target_temp_high: 76
      target_temp_low: 62

- alias: HVAC When Home
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_night
    to: disarmed
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_night
    to: armed_home
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: alarm_control_panel.area_001
    from: pending
    to: disarmed
  action:
  - service: climate.home
    data:
      entity_id: climate.master_suite
      target_temp_high: 79
      target_temp_low: 69

- alias: HVAC When Away
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: armed_away
  action:
  - service: climate.home
    data:
      entity_id: climate.master_suite
      target_temp_high: 82
      target_temp_low: 62
