input_boolean:
  hvac_geofence:
    name: In HVAC Geofence
    icon: mdi:crosshairs-gps
  hvac_guest_mode:
    name: HVAC Change in Gueat Mode

binary_sensor:
  - platform: template
    sensors:

      hvac_system_fan:
        unique_id: c0c5f690-6142-4f04-892d-27792ac70212
        friendly_name: "HVAC System Fan Call"
        value_template: '{{states.climate.thermostat.attributes.fan_action | string == "running" and states.climate.thermostat.attributes.hvac_action | string == "idle" }}'

      hvac_system_heat:
        unique_id: 27388e2b-ae8c-475c-909a-644e68591e3d
        friendly_name: "HVAC System Heat Call"
        value_template: '{{states.climate.thermostat.attributes.hvac_action | string == "heating" }}'

      hvac_system_cool:
        unique_id: 1ab31df8-73da-47dc-a4be-bcac83a20ac8
        friendly_name: "HVAC System Cool Call"
        value_template: '{{states.climate.thermostat.attributes.hvac_action | string == "cooling" }}'    

sensor:
  - platform: template
    sensors:
      hvac_system_state:
        unique_id: 8388a82f-3c13-4866-a9d0-d209ea80fb99
        friendly_name: "HVAC System Current State"
        value_template: >-
          {% if is_state("binary_sensor.hvac_system_cool", 'on') -%}
            Cool
          {% elif is_state("binary_sensor.hvac_system_heat", 'on') -%}
            Heat
          {% elif is_state("binary_sensor.hvac_system_fan", 'on') -%}
            Fan
          {%- else -%}
            Idle
          {%- endif %}
      
      hvac_system_runtime:
        unique_id: 466a6e61-c0aa-4994-a762-d08718665e72
        friendly_name: "HVAC Total System Runtime"
        unit_of_measurement: 'h'
        value_template: >-
          {{ ((states.sensor.hvac_system_fan_runtime.state | float) +
          (states.sensor.hvac_system_heat_runtime.state | float) +
          (states.sensor.hvac_system_cool_runtime.state | float)) | round(2) }}

  - platform: history_stats
    name: HVAC System Fan Runtime
    entity_id: binary_sensor.hvac_system_fan
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC System Heat Runtime
    entity_id: binary_sensor.hvac_system_heat
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: HVAC System Cool Runtime
    entity_id: binary_sensor.hvac_system_cool
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

automation:
  - alias: HVAC Night
    id: c8f44bcc-f9bc-4cd2-b9ba-f7a5810ec029
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: disarmed
        to: armed_night
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_home
        to: armed_night
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.thermostat
          target_temp_high: 75
          target_temp_low: 62
      - service: input_boolean.turn_off
        entity_id: input_boolean.hvac_guest_mode

  - alias: HVAC When Home
    id: b04a4cf4-5a5f-4af2-a473-d691fba74a23
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_away
        to: disarmed
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: pending
        to: disarmed
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.thermostat
          target_temp_high: 78
          target_temp_low: 69
      - service: input_boolean.turn_off
        entity_id: input_boolean.hvac_guest_mode

  - alias: HVAC When Waking
    id: 6cb3c69b-2e7d-4bcf-9e36-10bef104197a
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_night
        to: armed_home      
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_night
        to: disarmed
      - platform: state
        entity_id: input_boolean.karen_mode
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "off"
      - condition: state
        entity_id: input_boolean.karen_mode
        state: "off"
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.elkm1_house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.elkm1_house
            state: disarmed
          - condition: state
            entity_id: alarm_control_panel.elkm1_house
            state: arming
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.thermostat
          target_temp_high: 78
          target_temp_low: 69

  - alias: HVAC When Away
    id: 9e746040-d9f1-4756-8359-f4256906e67d
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        to: armed_away
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.thermostat
          target_temp_high: 82
          target_temp_low: 62
      - service: input_boolean.turn_off
        entity_id: input_boolean.hvac_guest_mode

  - alias: HVAC Off When Back Door Open
    id: 05dfec06-a230-4874-88bb-4bac4d1fdfc5
    trigger:
      - platform: state
        entity_id: sensor.elkm1_back_door_2
        to: Violated
        for:
          minutes: 5
    action:
      - service: climate.set_hvac_mode
        continue_on_error: true
        data:
          hvac_mode: 'off'
        target:
          entity_id: climate.thermostat
      - service: switch.turn_off
        continue_on_error: true
        entity_id: switch.den_fan

  - alias: HVAC On When Back Door Closed
    id: 8f9c905f-b015-4371-a286-beb6061317ae
    trigger:
      - platform: state
        entity_id: sensor.elkm1_back_door_2
        to: Normal
    condition:
      - condition: state
        entity_id: climate.thermostat
        state: 'off'
    action:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: 'auto'
        target:
          entity_id: climate.thermostat    