automation:
  # Add previous day's runtime to input_number each night
  - alias: Store HVAC runtime nightly
    id: f356d1e8-e46c-468d-9d47-6547e6900468
    trigger:
      - platform: time
        at: "00:00:01"
    action:
      - service: homeassistant.update_entity
        continue_on_error: true
        entity_id:
          - sensor.hvac_runtime_yesterday
          - sensor.hvac_runtime_today
      - service: input_number.set_value
        continue_on_error: true
        entity_id: input_number.hvac_runtime
        data_template:
          value: "{{ ((states('sensor.furnace_filter_life') | float(none)) + (states('sensor.hvac_runtime_yesterday') | float(none))) | round(1, default=none) }}"

  - alias: Reset Bleach Timer From NFC
    id: 96a5e35b-9980-4cf0-ba21-57651040c35c
    trigger:
      - platform: event
        event_type: tag_scanned
        event_data:
          tag_id: 0f411f83-399c-4ca7-9219-0039351d6e2d
    action:
      - service: script.furnace_bleach_date

  - alias: Record Last HVAC Cool Cycle
    id: 90c983c8-1f50-4471-9a38-e90d223805ce
    trigger:
      - platform: state
        entity_id: binary_sensor.hvac_system_cool
        to: "on"
    action:
      - service: input_text.set_value
        entity_id: input_text.furnace_last_cool
        data_template:
          value: "{{ now() }}"

template:
  - binary_sensor:
    - name: HVAC Running
      unique_id: d20886b2-98d0-41db-a308-72e6b7aa980b
      state: "{{ not is_state('sensor.hvac_system_state', 'Idle') }}"

    - name: HVAC Filter Needs Replacement
      unique_id: 7da223d0-0fa9-4910-8d98-80331861fed0
      state: "{{ states('sensor.furnace_filter_life') | int(none) > states('input_number.replacement_threshold') | int(none) }}"

    - name: HVAC Needs Bleach
      unique_id: 5a87c8f5-c05e-4641-9833-5eb2c8f5f85d
      state: >
        {% set x = states('sensor.time') %}
        {{ ((((as_timestamp(now(), none) - (as_timestamp(states.input_text.furnace_bleach.state, none))) | int(none) /60/1440) | round(0, default=none)) > 30) and ( (((as_timestamp(now(), none) - (as_timestamp(states.input_text.furnace_last_cool.state, none))) | int(none) /60/1440) | round(0, default=none)) <= 30 )}}

  - sensor:
      # Used to display current total runtime in frontend
    - name: Furnace Filter Life
      unique_id: 445057c0-592a-49f3-9268-4066339dfeff
      state: >
        {% set active = states('sensor.hvac_runtime_today') | float(none) %}
        {% set runtime = states('input_number.hvac_runtime') | float(none) %}
        {{ (runtime + active) | round(1, default=none) }}
      unit_of_measurement: "h"

      # Calculate average runtime in the last 7 days
    - name: Average Total Runtime Week
      unique_id: e123dec1-c3ed-411d-bc0d-eb6cea00be8e
      state: "{{ ((states('sensor.hvac_runtime_last_7_days') | float(none)) / 7) | round(2, default=none) }}"
      unit_of_measurement: "h"

      # Calculate number of days until filter will need to be changed based on replacement threshold and rolling average
    - name: Furnace Filter Days Remaining
      unique_id: 87ae7ed7-ac82-4b2a-a587-65c28df40db4
      state: >
        {% if (states('sensor.average_total_runtime_week') | float(none)) == 0 %}
          > 30
        {% elif ((((states('input_number.replacement_threshold') | float(none)) - (states('sensor.furnace_filter_life') | float(none))) / (states('sensor.average_total_runtime_week') | float(none))) | round(0, default=none)) > 30 %}
          > 30
        {% else %}
          {{ (((states('input_number.replacement_threshold') | float(none)) - (states('sensor.furnace_filter_life') | float(none))) / (states('sensor.average_total_runtime_week') | float(none))) | round(0, default=none) }}
        {% endif %}
      unit_of_measurement: "d"

    - name: Furnace Filter Last Replaced
      unique_id: 4d7e7fd7-496b-4a37-b0fe-f6a502be4595
      state: "{{ states('input_text.furnace_filter')[:10] }}"

    - name: Furnace Last Bleached
      unique_id: 13fbe76c-bbdb-48cc-a50a-dd018f912f2c
      state: "{{ states('input_text.furnace_bleach')[:10] }}"

    - name: Furnace Service Required
      unique_id: 0238c963-ab85-404c-8e5a-3f43c093f9c3
      state: >-
        {% if is_state('binary_sensor.hvac_needs_bleach', 'on') -%}
          Bleach
        {% elif is_state('binary_sensor.hvac_filter_needs_replacement', 'on') -%}
          Filter
        {% else -%}
          OK
        {% endif -%}

sensor:
  # Runtime yesterday (for use in storing runtime each night)
  - platform: history_stats
    name: HVAC runtime yesterday
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    duration:
      hours: 24
    end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"

  # Runtime current day before filter change script is called
  - platform: history_stats
    name: HVAC runtime before last filter change
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    start: "{{ as_timestamp(now().replace(hour=0).replace(minute=0).replace(second=0), none) }}"
    end: "{{ as_timestamp(states('input_text.furnace_filter'), none) }}"

  # Today's Runtime
  - platform: history_stats
    name: HVAC runtime today
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    end: "{{ now() }}"

  # Runtime last 7 days (for use in calculating rolling runtime average)
  - platform: history_stats
    name: HVAC runtime last 7 days
    entity_id: binary_sensor.hvac_running
    state: "on"
    type: time
    end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
    duration:
      days: 7

script:
  # Reset filter change date and set total runtime to zero
  furnace_filter_date:
    alias: Furnace filter change date
    sequence:
      - service: input_text.set_value
        continue_on_error: true
        entity_id: input_text.furnace_filter
        data_template:
          value: "{{ now() }}"
      - service: homeassistant.update_entity
        continue_on_error: true
        entity_id: sensor.hvac_runtime_before_last_filter_change
      - service: input_number.set_value
        continue_on_error: true
        entity_id: input_number.hvac_runtime
        data_template:
          value: >
            {% set active = (states('sensor.hvac_runtime_before_last_filter_change') | float(none)) %}
            {{ 0 - active }}
      - service: input_number.set_value
        continue_on_error: true
        entity_id: input_number.beginning_filter_dp
        data:
          value: 0
      - service: input_number.set_value
        continue_on_error: true
        entity_id: input_number.maximum_filter_dp
        data:
          value: 0
      - service: input_boolean.turn_on
        continue_on_error: true
        entity_id: input_boolean.record_beginning_dp

  furnace_bleach_date:
    alias: Furnace filter change date
    sequence:
      - service: input_text.set_value
        entity_id: input_text.furnace_bleach
        data_template:
          value: "{{ now() }}"

input_text:
  # Store furnace filter change date
  furnace_filter:
    name: Furnace Filter Change Date

  furnace_bleach:
    name: Furnace Last Bleach

  furnace_last_cool:
    name: Furnace Last Cooling

input_number:
  # Used to store runtime nightly to reduce reliance on history
  hvac_runtime:
    name: Runtime
    icon: mdi:clock-outline
    mode: box
    min: -1000
    max: 10000
    unit_of_measurement: "h"

  # Used to set max number of hours of filter runtime to calculate days until filter change required
  replacement_threshold:
    name: Threshold
    min: 0
    max: 10000
    mode: box
    unit_of_measurement: "h"

  beginning_filter_dp:
    name: Beginning Filter Differential
    min: 0
    max: 500
    mode: box
    unit_of_measurement: "Pa"

  maximum_filter_dp:
    name: Maximum Filter Differential
    min: 0
    max: 500
    mode: box
    unit_of_measurement: "Pa"

input_boolean:
  record_beginning_dp:
    name: Record Initial Filter Pressure