
- alias: All Off Main
  id: a29b6284-c1cf-4b82-935c-9b4d2fa224c1
  trigger:
  - platform: state
    entity_id: alarm_control_panel.house
    from: arming
    to: armed_away
  - platform: state
    entity_id: alarm_control_panel.house
    from: 
      - disarmed
      - armed_home
    to: armed_away
    for: "00:01:00"
  - platform: state
    entity_id: alarm_control_panel.house
    from: armed_home
    to: armed_night
  - platform: state
    entity_id: alarm_control_panel.house
    from: disarmed
    to: armed_night
  action:
  - service: swtich.turn_off
    data:
      entity_id: switch.left_back_porch
  - service: switch.turn_off
    data:
      entity_id: switch.right_back_porch

- alias: All Off Timer Lights
  id: 1ee390dc-5453-470d-9ff8-e88a8f8cd641
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.all_off_main
  condition:
  - condition: state
    entity_id: input_boolean.timer_lights
    state: 'off'
  action:
  - service: switch.turn_off
    entity_id: 
      - switch.guest_room_lamp
      - switch.craft_room_table_lamp
      - switch.den_curio_cabinet
      - switch.master_bedroom_lamp
  - service: light.turn_off
    entity_id:
      - light.watch_shop_lamp
      - light.craft_room_floor_lamp
      - light.entry_lamp
      - light.den_table_lampmp

- alias: All Off Outside Lights
  id: e6af1bb3-8d93-4ed5-a8ad-7e10328468b4
  trigger:
  - platform: event
    event_type: automation_triggered
    event_data:
      entity_id: automation.all_off_main
  condition:
  - condition: state
    entity_id: input_boolean.outside_timer_lights
    state: 'off'
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.outside_lights