- alias: Indoor Christmas On When Home
  id: 1a134ab1-f2c9-4c89-90c1-f8ca73da8b46
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: disarmed
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: armed_home
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.christmas_tree

- alias: Indoor Christmas Off When Away or Asleep
  id: 63914fe0-40f3-4124-b94c-15abc036a79a
  trigger:
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: armed_away
  - platform: state
    entity_id: alarm_control_panel.area_001
    to: armed_night
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.christmas_tree
