- alias: Elk Night Mode On from Trigger
  id: e70dcf76-34cc-460f-accd-66c4465a4672
  trigger:
    - platform: state
      entity_id: input_boolean.elk_night_on
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.elkm1_house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.elkm1_house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id: switch.elkm1_output_178
    - service: input_boolean.turn_off
      continue_on_error: true
      entity_id: input_boolean.elk_night_on

- alias: Elk Night Mode Off from Trigger
  id: 1cada28e-68d9-4009-877e-248cc6b80182
  trigger:
    - platform: state
      entity_id: input_boolean.elk_night_off
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.elkm1_house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.elkm1_house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id: switch.elkm1_output_177
    - service: input_boolean.turn_off
      continue_on_error: true
      entity_id: input_boolean.elk_night_off  

- alias: Elk Stay Mode On from Trigger
  id: d074bb20-fbc8-459e-a8ec-3f113e53b305
  trigger:
    - platform: state
      entity_id: input_boolean.elk_stay_on
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.elkm1_house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.elkm1_house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id: switch.elkm1_output_177
    - service: input_boolean.turn_off
      continue_on_error: true
      entity_id: input_boolean.elk_stay_on

- alias: Elk Stay Mode Off from Trigger
  id: 8d7082ab-3db5-4f9e-9f94-6b9bd164250b
  trigger:
    - platform: state
      entity_id: input_boolean.elk_stay_off
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.elkm1_house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.elkm1_house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id: switch.elkm1_output_180
    - service: input_boolean.turn_off
      continue_on_error: true
      entity_id: input_boolean.elk_stay_off      

- alias: Elk Away Mode On from Trigger
  id: 4f80ec1b-a8cf-427f-8900-ca5ee23bc57a
  trigger:
    - platform: state
      entity_id: input_boolean.elk_away_on
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state_attr('alarm_control_panel.elkm1_house', 'alarm_state', 'no_alarm_active') }}"
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.elkm1_house', 'armed_away') }}"
  action:
    - service: switch.turn_on
      continue_on_error: true
      entity_id: switch.elkm1_output_179
    - service: input_boolean.turn_off
      continue_on_error: true
      entity_id: input_boolean.elk_away_on    

- alias: Elk Clear Trigger if State Disallowed
  id: c85727a7-5132-4a0a-a260-2e39fec21d56
  trigger:
    - platform: state
      entity_id: input_boolean.elk_night_on
      to: 'on'
    - platform: state
      entity_id: input_boolean.elk_night_off
      to: 'on'
    - platform: state
      entity_id: input_boolean.elk_stay_on
      to: 'on'
    - platform: state
      entity_id: input_boolean.elk_stay_off
      to: 'on'
    - platform: state
      entity_id: input_boolean.elk_away_on
      to: 'on'
  condition:
    - condition: or
      conditions:
      - condition: template
        value_template: "{{ not is_state_attr('alarm_control_panel.elkm1_house', 'alarm_state', 'no_alarm_active') }}"
      - condition: template
        value_template: "{{ is_state('alarm_control_panel.elkm1_house', 'armed_away') }}"
  action:
    - service: input_boolean.turn_off
      continue_on_error: true
      entity_id: 
        - input_boolean.elk_night_on   
        - input_boolean.elk_night_off
        - input_boolean.elk_stay_on     
        - input_boolean.elk_stay_off
        - input_boolean.elk_away_on