# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Announcements
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
- alias: 'Announce Dryer Finished'
  id: c790a0d0-8a98-425c-afa8-15aea2994b89
  trigger:
    platform: state
    entity_id: binary_sensor.dryer_dry_completed
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.elkm1_house
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.elkm1_house
        state: 'armed_home'
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 3
        file: 1

- alias: 'Announce Washer Finished'
  id: 2de2b07e-f754-4667-a620-de035f87cc61
  trigger:
    platform: state
    entity_id: binary_sensor.washer_wash_completed
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.elkm1_house
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.elkm1_house
        state: 'armed_home'
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 3
        file: 3
