- alias: 'Dryer State - Door'
  id: 2b2bbced-7673-4944-9199-82a1b9936d71
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_watts
    above: 5
    below: 20
    for:
      seconds: 2
  action:
    - service: mqtt.publish
      data:
        topic: hass/state/dryer
        payload: 'Door Open'
        retain: 'true'

- alias: 'Dryer State - Drying'
  id: c6b0a8b2-8c82-4098-ae93-c9fb8956d86f
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_watts
    above: 50
    for:
      seconds: 2
  action:
    - service: mqtt.publish
      data:
        topic: hass/state/dryer
        payload: 'Drying'
        retain: 'true'
    - service: input_boolean.turn_off
      entity_id: input_boolean.dryer_end

- alias: 'Dryer State - Idle'
  id: c0484d8c-fd9c-4556-9a46-1d8589483209
  trigger:
    platform: numeric_state
    entity_id: sensor.dryer_watts
    below: 5
    for:
      seconds: 2
  action:
    - service: mqtt.publish
      data:
        topic: hass/state/dryer
        payload: 'Idle'
        retain: 'true'

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Washing Machine Start/Finish
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
- alias: 'Washer State - Start'
  id: ebebbad4-b704-41b3-ac4d-7507e957f23e
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    above: 20
    for:
      seconds: 10
# Make sure washer isn't already running and delaying between cycles - don't re-trigger and cause stopwatch reset
  condition:
    condition: template
    value_template: "{{ states.sensor.washer_state.state != 'Washing' }}"
  action:
    - service: mqtt.publish
      data:
        topic: hass/state/washer
        payload: 'Washing'
        retain: 'true'
    - service: input_boolean.turn_off
      entity_id: input_boolean.washer_end

- alias: 'Washer State - Idle'
  id: 28708a17-80cd-4683-badb-5d5f1ac54526
  trigger:
    platform: numeric_state
    entity_id: sensor.washer_watts
    below: 20
    for:
      minutes: 2
  action:
    - service: mqtt.publish
      data:
        topic: hass/state/washer
        payload: 'Idle'
        retain: 'true'

- alias: 'Dryer Finished'
  id: 808d187b-2175-4158-9da7-f968751e74c4
  trigger:
    platform: state
    entity_id: sensor.dryer_state
    from: 'Drying'
    to: 'Idle'
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.dryer_end

- alias: 'Washer Finished'
  id: 54daac37-84fa-4d7c-9337-43bef0bc952a
  trigger:
    platform: state
    entity_id: sensor.washer_state
    from: 'Washing'
    to: 'Idle'
  condition:
    condition: template
    value_template: "{{ states.sensor.dryer_state.state != 'Drying' }}"
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.washer_end

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Announcements
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
- alias: 'Announce Dryer Finished'
  id: c790a0d0-8a98-425c-afa8-15aea2994b89
  trigger:
    platform: state
    entity_id: input_boolean.dryer_end
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'armed_home'
  action:
    - service: notify.browser
      data:
        message: The dryer has stopped.
        title: Laundry Update
    - service: notify.alexa_media
      data:
        message: "The dryer has stopped."
        data:
          type: announce
          method: all
        target:
          - media_player.alexa_craft
          - media_player.alexa_master
          - media_player.alexa_kitchen
    - service: input_boolean.turn_off
      entity_id: input_boolean.dryer_end

- alias: 'Announce Washer Finished'
  id: 2de2b07e-f754-4667-a620-de035f87cc61
  trigger:
    platform: state
    entity_id: input_boolean.washer_end
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'armed_home'
  action:
    - service: notify.browser
      data:
        message: The washer has stopped.
        title: Laundry Update
    - service: notify.alexa_media
      data:
        message: "The Washer has stopped."
        data:
          type: announce
          method: all
        target:
          - media_player.alexa_craft
          - media_player.alexa_master
          - media_player.alexa_kitchen
    - service: input_boolean.turn_off
      entity_id: input_boolean.washer_end