# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
#  Announcements
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
- alias: 'Announce Dryer Finished'
  id: c790a0d0-8a98-425c-afa8-15aea2994b89
  trigger:
    platform: state
    entity_id: binary_sensor.dryer_dry_completed
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'armed_home'
  action:
    - service: notify.browser
      data:
        message: The dryer has stopped.
        title: Laundry Update
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 3,1

- alias: 'Announce Washer Finished'
  id: 2de2b07e-f754-4667-a620-de035f87cc61
  trigger:
    platform: state
    entity_id: binary_sensor.washer_wash_completed
    to: 'on'
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'disarmed'
      - condition: state
        entity_id: alarm_control_panel.house
        state: 'armed_home'
  action:
    - service: notify.browser
      data:
        message: The washer has stopped.
        title: Laundry Update
    - service: mqtt.publish
      data:
        topic: parrot/command/set/play
        payload: 3,3
