- alias: Elk Speak Front Door
  id: c9af2838-3b15-451e-a2f3-89c738fdd65a
  trigger:
    - entity_id: sensor.elk_front_door
      platform: state
      to: Violated
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 1
        file: 7

- alias: Elk Speak Back Door
  id: fd4f76b2-f24c-4e6a-b3ff-50f1e9fc5759
  trigger:
    - entity_id: sensor.elk_back_door
      platform: state
      to: Violated
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 1
        file: 2

- alias: Elk Speak Garage Door
  id: 6945273c-ae6f-45aa-b99f-f5c71726ee29
  trigger:
    - entity_id: sensor.elk_garage_door
      platform: state
      to: Violated
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 1
        file: 9

- alias: Elk Speak Garage Entry
  id: 74a00540-b7f9-4cf2-87cd-4673042418d0
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('sensor.elk_garage_entry', 'physical_status', 'open') }}"
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 1
        file: 10

- alias: Elk Speak Armed Stay
  id: 85ccbd29-b857-4ef3-888d-3f8a38f8d901
  trigger:
    - entity_id: alarm_control_panel.house
      from: disarmed
      platform: state
      to: armed_home
    - entity_id: alarm_control_panel.house
      from: armed_night
      platform: state
      to: armed_home
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 12

- alias: Elk Speak Armed Away
  id: 054c3121-c453-45a5-8279-8c1036c6a01b
  trigger:
    - entity_id: alarm_control_panel.house
      from: disarmed
      platform: state
      to: armed_away
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 5
    - delay: "00:00:48"
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 13

- alias: Elk Speak Armed Vacation
  id: 08bb2dee-574d-4e46-a206-84bb7da159e4
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('alarm_control_panel.house', 'armed_status', 'armed_to_vacation') }}"
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 14
    - delay: "00:00:48"
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 13
- alias: Elk Speak Armed Night
  id: d06423ff-1f43-402f-9227-29065ccbb0c6
  trigger:
    - entity_id: alarm_control_panel.house
      from: disarmed
      platform: state
      to: armed_night
    - entity_id: alarm_control_panel.house
      from: armed_home
      platform: state
      to: armed_night
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 9

- alias: Elk Speak Disarmed
  id: 585db9cd-f804-4a97-9497-83864244f61e
  trigger:
    - entity_id: alarm_control_panel.house
      platform: state
      to: disarmed
  condition:
    - condition: state
      entity_id: input_boolean.elk_speech
      state: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 2
        file: 2

- alias: Doorbell Alert
  id: e6b77810-e307-45ce-96d2-8ef3961aafb8
  trigger:
    - platform: mqtt
      topic: amcrest2mqtt/Z05919E169440/doorbell
      payload: "on"
  action:
    - service: esphome.elkspeak_dfplayer_play_folder
      data:
        folder: 4
        file: 1
    - service: browser_mod.popup
      data:  
        auto_close: true
        timeout: 30000
        content:
          type: horizontal-stack
          cards:
            - type: picture-entity
              show_state: false
              show_name: false        
              entity: camera.front_porch

- alias: Disable Speech at Night if Dad Home
  id: a2eaf102-55ee-4ed9-9893-a4cc4e9c4764
  trigger:
    - platform: time
      at: "22:00:00"
  condition:
    - condition: state
      entity_id: person.scott_mccoy
      state: home
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.elk_speech

- alias: Enable Speech in Morning
  id: 7f4d76a0-b434-4e01-866f-1c31b5715a55
  trigger:
    - platform: time
      at: "07:00:00"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.elk_speech