- alias: Tablet Night
  id: 1b92d6b5-aa22-48f1-9dc4-66661bbdfc7b
  trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      from: armed_home
      to: armed_night
  action:
    - service: script.tablets_off

- alias: Tablet When Home
  id: 63a211c7-b83d-49f6-afdd-7c0f9c11176f
  trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      from: armed_night
      to: armed_home
  action:
    - service: script.tablets_on

- alias: Tablet when Away
  id: 85ff81d4-cc3f-491b-a8d3-79aadc40302c
  trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: armed_away
  action:
    - service: script.tablets_off

- alias: Tablet Early Morning
  id: 7bdf3dd9-80b8-4264-b07b-3d9d6c0cf69c
  trigger:
    - platform: state
      entity_id: binary_sensor.den_motion_occupancy
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.elkm1_house
      state: armed_night
  action:
    - service: light.turn_on
      entity_id: light.den_tablet_screen

- alias: Reload Tablets When HA Starts
  id: b05068bb-8447-408b-8cef-1557cdafa888
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.tablets_reload
