- alias: Tablet Night
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: armed_home
      to: armed_night
  action:
    - service: script.tablets_off

- alias: Tablet When Home
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: armed_night
      to: armed_home
  action:
    - service: script.tablets_on

- alias: Tablet when Away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      to: armed_away
  action:
    - service: script.tablets_off

- alias: Tablet Early Morning
  trigger:
    - platform: time
      at: "05:00:00"
  condition:
    - condition: state
      entity_id: alarm_control_panel.area_001
      state: armed_night
  action:
    - service: rest_command.den_tablet_on
