- alias: Tablet Night
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: disarmed
      to: armed_night
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: armed_home
      to: armed_night
  action:
    - service: script.tablets_off

- alias: Tablet When Home
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.area_001
      from: armed_night
      to: armed_home
  action:
    - service: script.tablets_on

- alias: Tablet when Away
  trigger:
    - platform: state
      entity_id: alarm_control_panel.area_001
      to: armed_away
  action:
    - service: script.tablets_off

- alias: Tablet Early Morning
  trigger:
    - platform: state
      entity_id: binary_sensor.den_motion_occupancy
      from: "off"
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.area_001
      state: armed_night
  action:
    - service: rest_command.den_tablet_on

- alias: Reload Tablets When HA Starts
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.tablets_reload
