utility_meter:
  adguard_queries_daily:
    source: sensor.adguard_main_dns_queries_today
    cycle: daily

  adguard_blocked_daily:
    source: sensor.adguard_main_dns_queries_blocked_today
    cycle: daily

sensor:
  - platform: template
    sensors:
      adguard_dummy:
        unique_id: 02b3c006-027a-4e7e-b14b-0c826c27e387
        value_template: ""
        friendly_name: ""    

mqtt:
  sensor:
    - name: AdGuard Main Average Processing Speed
      unique_id: 695b6e31-70b8-48b0-8285-34e3c1a6cd33
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['dns'].process_time }}"
      unit_of_measurement: ms

    - name: AdGuard Main DNS Queries Today
      unique_id: 6016dc4d-9d37-4b99-88bb-c29a1a777452
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['dns'].query_day }}"
      unit_of_measurement: queries

    - name: AdGuard Main DNS Queries This Hour
      unique_id: 921f3277-0af9-494c-aa78-e899da4bbc97
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['dns'].query_hour }}"
      unit_of_measurement: queries

    - name: AdGuard Main DNS Queries Last Hour
      unique_id: c7f48d50-70a5-48ea-8e62-1aa9142ae375
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['dns'].query_last_hour }}"
      unit_of_measurement: queries

    - name: AdGuard Main DNS Block Ratio
      unique_id: 413e6d35-522a-439f-9acd-096db1c66812
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['filter'].block_ratio }}"
      unit_of_measurement: "%"

    - name: AdGuard Main DNS Queries Blocked Today
      unique_id: 2b9d9ad3-1ab9-4204-aa48-b953abd041b6
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['filter'].blocked_day }}"
      unit_of_measurement: queries

    - name: AdGuard Main DNS Queries Blocked This Hour
      unique_id: a0af9373-3f37-4210-bcdf-e2f3c2762768
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['filter'].blocked_hour }}"
      unit_of_measurement: queries

    - name: AdGuard Main DNS Queries Blocked Last Hour
      unique_id: ceb6a1f7-7d49-45f2-afce-e0aed133f436
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['filter'].blocked_last_hour }}"
      unit_of_measurement: queries

    - name: AdGuard Main Safe Browsing Blocked Today
      unique_id: 2bc594d1-1713-47ee-904a-268120872d66
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['browsing'].blocked_day }}"
      unit_of_measurement: queries

    - name: AdGuard Main Safe Browsing Blocked This Hour
      unique_id: 38d9090c-5352-4582-a2e2-503f4fea9858
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['browsing'].blocked_hour }}"
      unit_of_measurement: queries

    - name: AdGuard Main Safe Browsing Blocked Last Hour
      unique_id: a74658c1-f633-47ef-b1c9-988afeb38198
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['browsing'].blocked_last_hour }}"
      unit_of_measurement: queries

    - name: AdGuard Main Safe Search Blocked Today
      unique_id: 1dec1b6a-0cc4-45ab-926a-f8c9b49ed6fa
      state_topic: adguard/main/tele/stats
      value_template: "{{value_json['search'].blocked_day }}"
      unit_of_measurement: queries

  switch:
    - name: AdGuard Main Protection
      unique_id: a751b3e1-0635-4476-af96-abd088902135
      state_topic: "adguard/main/tele/stats"
      command_topic: "adguard/main/command/set/protection"
      value_template: "{{value_json['protection_enabled']}}"
      payload_on: "true"
      payload_off: "false"
    
    - name: AdGuard Main Filtering
      unique_id: fa5b4591-1827-4dec-919a-cfdc4bdea6cd
      state_topic: "adguard/main/tele/stats"
      command_topic: "adguard/main/command/set/filter"
      value_template: "{{value_json['filter'].enabled}}"
      payload_on: "true"
      payload_off: "false"
    
    - name: AdGuard Main Parental Control
      unique_id: bc9a4d9d-a3c1-40e0-a4c1-9398a5c70236
      state_topic: "adguard/main/tele/stats"
      command_topic: "adguard/main/command/set/parental"
      value_template: "{{value_json['parental'].enabled}}"
      payload_on: "true"
      payload_off: "false"

    - name: AdGuard Main Safe Browsing
      unique_id: d4421052-53a6-4b77-bc0e-10124ee96ddb
      state_topic: "adguard/main/tele/stats"
      command_topic: "adguard/main/command/set/browsing"
      value_template: "{{value_json['browsing'].enabled}}"
      payload_on: "true"
      payload_off: "false"
    
    - name: AdGuard Main Safe Search
      unique_id: b7758c41-88eb-427e-a5c0-8a0f7b2a593d
      state_topic: "adguard/main/tele/stats"
      command_topic: "adguard/main/command/set/search"
      value_template: "{{value_json['search'].enabled}}"
      payload_on: "true"
      payload_off: "false"