switch:

  - platform: mqtt
    name: "Christmas Tree"
    state_topic: "christmas/indoor/tree/stat/POWER"
    command_topic: "christmas/indoor/tree/cmnd/POWER"
    availability_topic: "christmas/indoor/tree/tele/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

sensor:

  - platform: mqtt
    state_topic: "christmas/indoor/tree/tele/STATE"
    name: "Chriatmas Tree Signal"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "christmas/indoor/tree/tele/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline" 
