switch:
  - platform: template
    switches:
      indoor_christmas:
        unique_id: a37d4c37-0a83-47f6-9389-164dfc4d954b
        friendly_name: "Indoor Christmas Decor"
        value_template: "{{ is_state('switch.christmas_1', 'on') or is_state('switch.christmas_2', 'on') or is_state('switch.christmas_3', 'on') or is_state('switch.christmas_4', 'on') or is_state('switch.christmas_5', 'on') }}"
        turn_on:
          service: mqtt.publish
          data:
            topic: cmnd/decorations/power
            payload: "ON"
        turn_off:
          service: mqtt.publish
          data:
            topic: cmnd/decorations/power
            payload: "OFF"

automation:
  - alias: Indoor Christmas On When Home
    id: 1a134ab1-f2c9-4c89-90c1-f8ca73da8b46
    trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: armed_home
    action:
    - service: switch.turn_on
      data:
        entity_id: switch.indoor_christmas

  - alias: Indoor Christmas Off When Away or Asleep
    id: 63914fe0-40f3-4124-b94c-15abc036a79a
    trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: armed_away
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: armed_night
    action:
    - service: switch.turn_off
      data:
        entity_id: switch.indoor_christmas
    - service: mqtt.publish
      data:
        topic: cmnd/allir/irsend
        payload: '{"Protocol":"NEC","Bits":32,"Data":"0x00FF629D"}'

  - alias: Christmas Lights On
    id: 7b933f59-ee4c-45fe-a26c-c50aafb4a7bb
    trigger:
      - platform: mqtt
        topic: christmas/show
        payload: "ON"
    action:
      - service: switch.turn_off
        entity_id: 
          - switch.outside_lights
          - switch.guest_room_lamp
      - service: switch.turn_on
        entity_id: switch.christmas_outlets

  - alias: Christmas Lights Off
    id: 87e03159-71a3-4978-9cee-5d0c65102900
    trigger:
      - platform: mqtt
        topic: christmas/show
        payload: "OFF"
    action:
      - service: switch.turn_off
        entity_id: switch.christmas_outlets
      - service: switch.turn_on
        entity_id: switch.outside_lights

  - alias: Candles On at Dark When Home
    id: c11f19c4-c6d8-4e70-b07d-c14ab6804f63
    trigger:
      - platform: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: -3
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: alarm_control_panel.elkm1_house
            state: armed_home
          - condition: state
            entity_id: alarm_control_panel.elkm1_house
            state: disarmed
    action:
      - service: mqtt.publish
        data:
          topic: cmnd/allir/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE48B7"}'
      - delay:
          seconds: 10
      - service: mqtt.publish
        data:
          topic: cmnd/allir/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x00FFA25D"}'

  - alias: Candles On at When Returning After Dark
    id: 23e950df-a5c1-4ca7-8c7d-e87d4c619cde
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: pending
        to: disarmed
    condition:
      - condition: sun
        after: sunset
        after_offset: "00:30:00"
    action:
      - service: mqtt.publish
        data:
          topic: cmnd/allir/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x1FE48B7"}'
      - delay:
          seconds: 10
      - service: mqtt.publish
        data:
          topic: cmnd/allir/irsend
          payload: '{"Protocol":"NEC","Bits":32,"Data":"0x00FFA25D"}'
