mqtt:
  switch:
    - name: "Christmas Tree"
      unique_id: a2a76d1f-ff61-414d-a04d-daae35d443ea
      state_topic: "christmas/indoor/tree/stat/POWER"
      command_topic: "christmas/indoor/tree/cmnd/POWER"
      availability_topic: "christmas/indoor/tree/tele/LWT"
      qos: 1
      payload_on: "ON"
      payload_off: "OFF"
      payload_available: "Online"
      payload_not_available: "Offline"

  sensor:
    - name: "Chriatmas Tree Signal"
      unique_id: 768fd9b4-364c-4b03-ad60-925cc69df653
      state_topic: "christmas/indoor/tree/tele/STATE"
      unit_of_measurement: "%"
      value_template: "{{value_json['Wifi'].RSSI }}"
      availability_topic: "christmas/indoor/tree/tele/LWT"
      qos: 1
      payload_available: "Online"
      payload_not_available: "Offline" 

automation:
  - alias: Indoor Christmas On When Home
    id: 1a134ab1-f2c9-4c89-90c1-f8ca73da8b46
    trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: disarmed
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_home
    action:
    - service: switch.turn_on
      data:
        entity_id: switch.christmas_tree

  - alias: Indoor Christmas Off When Away or Asleep
    id: 63914fe0-40f3-4124-b94c-15abc036a79a
    trigger:
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_away
    - platform: state
      entity_id: alarm_control_panel.house
      to: armed_night
    action:
    - service: switch.turn_off
      data:
        entity_id: switch.christmas_tree

  - alias: Christmas Lights On
    id: 7b933f59-ee4c-45fe-a26c-c50aafb4a7bb
    trigger:
      - platform: mqtt
        topic: christmas/show
        payload: "ON"
    action:
      - service: switch.turn_off
        entity_id: switch.outside_lights
      - service: switch.turn_on
        entity_id: switch.christmas_outlets

  - alias: Christmas Lights Off
    id: 87e03159-71a3-4978-9cee-5d0c65102900
    trigger:
      - platform: mqtt
        topic: christmas/show
        payload: "OFF"
    action:
      - service: switch.turn_off
        entity_id: switch.christmas_outlets
      - service: switch.turn_on
        entity_id: switch.outside_lights
