timer:
  front_door_dho:
    name: Front Door Alert Timer
    duration: "00:05:00"
  back_door_dho:
    name: Back Door Alert Timer
    duration: "00:05:00"
  garage_entry_dho:
    name: Garage Entry Alert Timer
    duration: "00:05:00"

input_boolean:
  front_door_alert_type:
    name: Front Door Alert Type
    icon: mdi:timer-outline   
  back_door_alert_type:
    name: Back Door Alert Type
    icon: mdi:timer-outline   
  garage_entry_alert_type:
    name: Garage Entry Alert Type
    icon: mdi:timer-outline    

template:
  - binary_sensor:
    - name: Front Door Status
      unique_id: 1a7ff7f2-1134-4d72-90c6-10238de5d2b2
      state: "{{ not is_state('sensor.elk_front_door', 'Normal') }}"
      device_class: door
    
    - name: Back Door Status
      unique_id: b4ac6167-b0e8-4f8a-99b4-89c41889887c
      state: "{{ not is_state('sensor.elk_back_door', 'Normal') }}"
      device_class: door
    
    - name: Garage Entry Status
      unique_id: bffc8a9a-06df-4ade-80d2-520686d40751
      state: "{{ not is_state('sensor.elk_garage_entry', 'Normal') }}"
      device_class: door

automation:
  - alias: Start Front Door Alert Timer When Door Open
    id: 8e046181-6edd-4356-b7d5-3f8ed70df1c1
    trigger:
      - platform: state
        entity_id: sensor.elk_front_door
        to: Violated
    action:
      - service: timer.start
        entity_id: timer.front_door_dho

  - alias: Start Back Door Alert Timer When Door Open
    id: da2fdce5-0820-4428-8a5f-84f735fb768a
    trigger:
      - platform: state
        entity_id: sensor.elk_back_door
        to: Violated
    action:
      - service: timer.start
        entity_id: timer.back_door_dho

  - alias: Start Garage Entry Alert Timer When Door Open
    id: b4cc6522-12e1-4b2a-b65a-2148ae1aad10
    trigger:
      - platform: state
        entity_id: sensor.elk_garage_entry
        to: Violated
    action:
      - service: timer.start
        entity_id: timer.garage_entry_dho

  - alias: Cancel Front Door Alert Timer When Door Open
    id: 5dabaa11-d4e7-45bb-a6f6-57b5e237e6bc
    trigger:
      - platform: state
        entity_id: sensor.elk_front_door
        to: Normal
    action:
      - service: timer.cancel
        entity_id: timer.front_door_dho
      - service: input_boolean.turn_off
        entity_id: input_boolean.front_door_alert_type

  - alias: Cancel Back Door Alert Timer When Door Open
    id: 3d08fe25-ca53-42db-833e-b30ef14658e4
    trigger:
      - platform: state
        entity_id: sensor.elk_back_door
        to: Normal
    action:
      - service: timer.cancel
        entity_id: timer.back_door_dho
      - service: input_boolean.turn_off
        entity_id: input_boolean.back_door_alert_type

  - alias: Cancel Garage Entry Alert Timer When Door Open
    id: 42549bef-bb19-4fb2-ace3-4ee31a28dc90
    trigger:
      - platform: state
        entity_id: sensor.elk_garage_entry
        to: Normal
    action:
      - service: timer.cancel
        entity_id: timer.garage_entry_dho
      - service: input_boolean.turn_off
        entity_id: input_boolean.garage_entry_alert_type

  - alias: Announce Front Door Alert When Timer Ends
    id: 9b8f662f-bbfc-41b4-9249-ef276e778233
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.front_door_dho
    action:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.front_door_alert_type
            state: "off"
          sequence:
            - service: esphome.elkspeak_dfplayer_play_folder
              data:
                folder: 1
                file: 7
            - service: input_boolean.turn_on
              entity_id: input_boolean.front_door_alert_type
        - conditions:
          - condition: state
            entity_id: input_boolean.front_door_alert_type
            state: "on"
          sequence:
            - service: switch.turn_on
              entity_id: switch.entry_siren
            - delay: 10
            - service: switch.turn_off
              entity_id: switch.entry_siren
            - service: notify.mobile_app_hd1907
              data:
                title: Door Alert
                message: The front door has been left open.
            - service: input_boolean.turn_off
              entity_id: input_boolean.front_door_alert_type
      - service: timer.start
        entity_id: timer.front_door_dho

  - alias: Announce Back Door Alert When Timer Ends
    id: 1c7c7a14-96d0-43af-8a9c-285b63e9fb25
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.back_door_dho
    action:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.back_door_alert_type
            state: "off"
          sequence:
            - service: esphome.elkspeak_dfplayer_play_folder
              data:
                folder: 1
                file: 2
            - service: input_boolean.turn_on
              entity_id: input_boolean.back_door_alert_type
        - conditions:
          - condition: state
            entity_id: input_boolean.back_door_alert_type
            state: "on"
          sequence:
            - service: switch.turn_on
              entity_id: switch.entry_siren
            - delay: 10
            - service: switch.turn_off
              entity_id: switch.entry_siren
            - service: notify.mobile_app_hd1907
              data:
                title: Door Alert
                message: The back door has been left open.
            - service: input_boolean.turn_off
              entity_id: input_boolean.back_door_alert_type
      - service: timer.start
        entity_id: timer.back_door_dho

  - alias: Announce Garage Entry Alert When Timer Ends
    id: 626da9af-6737-4dbf-9bf6-4d18f003b194
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.garage_entry_dho
    action:
      - choose:
        - conditions:
          - condition: state
            entity_id: input_boolean.garage_entry_alert_type
            state: "off"
          sequence:
            - service: esphome.elkspeak_dfplayer_play_folder
              data:
                folder: 1
                file: 10
            - service: input_boolean.turn_on
              entity_id: input_boolean.garage_entry_alert_type
        - conditions:
          - condition: state
            entity_id: input_boolean.garage_entry_alert_type
            state: "on"
          sequence:
            - service: switch.turn_on
              entity_id: switch.entry_siren
            - delay: 10
            - service: switch.turn_off
              entity_id: switch.entry_siren
            - service: notify.mobile_app_hd1907
              data:
                title: Door Alert
                message: The garage entry has been left open.
            - service: input_boolean.turn_off
              entity_id: input_boolean.garage_entry_alert_type
      - service: timer.start
        entity_id: timer.garage_entry_dho