cover:
  - platform: template
    covers:
      garage_door:
        unique_id: b2c4cd4a-3ac2-4d33-98c3-02b05394a01f
        device_class: garage
        friendly_name: Garage Door
        value_template: "{{ not is_state('sensor.elkm1_garage_door', 'Normal') }}"
        open_cover:
          service: switch.turn_on
          entity_id: switch.garage_door_opener
        close_cover:
          service: switch.turn_on
          entity_id: switch.garage_door_opener

automation:
  - alias: Trigger Garage Door Opener From Elk
    id: d2d3f74b-1fd2-45b8-b563-ac0d4fbd8691
    trigger:    
      - platform: state
        entity_id: switch.garage_door
        from: 'off'
        to: 'on'
    action:
      - service: switch.turn_on
        entity_id: switch.garage_door_opener