input_boolean:
  guest_phone_connected:
    name: Guest Room Phone Connected
    initial: off
    icon: mdi:power-socket

# Sensors
mqtt:
  sensor:
    #Sonoff Guest Charger Monitor
    - name: "Guest Charger Watts"
      unique_id: 0000eaea-f4db-476e-9503-b8b52b69cab4
      state_topic: "guest-charger/tele/SENSOR"
      value_template: "{{value_json['ENERGY'].Power }}"
      qos: 2
      unit_of_measurement: "W"
      icon: mdi:flash-circle
      availability_topic: "guest-charger/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Guest Charger Voltage"
      unique_id: 5fbee6b2-e70f-4f53-88a4-51cb3aea92f6
      state_topic: "guest-charger/tele/SENSOR"
      value_template: "{{value_json['ENERGY'].Voltage }}"
      qos: 2
      unit_of_measurement: "V"
      icon: mdi:flash-circle
      availability_topic: "guest-charger/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Guest Charger Amps"
      unique_id: 248fc6cc-3630-4d3a-bd5f-01812d8bf1de
      state_topic: "guest-charger/tele/SENSOR"
      value_template: "{{value_json['ENERGY'].Current }}"
      qos: 2
      unit_of_measurement: "A"
      icon: mdi:flash-circle
      availability_topic: "guest-charger/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Guest Charger Energy Today"
      unique_id: 1dbc5e52-e90e-42d0-b47c-7b024249c855
      state_topic: "guest-charger/tele/SENSOR"
      value_template: "{{value_json['ENERGY'].Today }}"
      qos: 2
      unit_of_measurement: "kWh"
      availability_topic: "guest-charger/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - name: "Guest Charger Energy Yesterday"
      unique_id: f288da2e-78c1-41ac-8a52-1af7fbf8be84
      state_topic: "guest-charger/tele/SENSOR"
      value_template: "{{value_json['ENERGY'].Yesterday }}"
      qos: 2
      unit_of_measurement: "kWh"
      availability_topic: "guest-charger/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

    - state_topic: "guest-charger/tele/STATE"
      unique_id: 07989283-a572-4a24-a890-fdc6179acf65
      name: "Guest Charger Signal"
      unit_of_measurement: "%"
      value_template: "{{value_json['Wifi'].RSSI }}"
      availability_topic: "guest-charger/tele/LWT"
      qos: 1
      payload_available: "Online"
      payload_not_available: "Offline"

automation:
  - alias: Guest Mode On from Keypad
    id: b4543958-2736-46c0-b13a-1eecbce1acd1
    trigger:
      - platform: state
        entity_id: switch.guest_mode
        from: "off"
        to: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode

  - alias: Guest Mode Off from Keypad
    id: bea19440-acfa-4105-99a9-9ebc8566336f
    trigger:
      - platform: state
        entity_id: switch.guest_mode
        from: "on"
        to: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode

  - alias: Guest Mode Keypad On
    id: 4c39b750-5544-4f74-94bd-e8ee163eae49
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.guest_mode
        state: "off"
    action:
      - service: switch.turn_on
        entity_id: switch.guest_mode

  - alias: Guest Mode Keypad Off
    id: 44f68f4a-4c89-4b7c-8471-a73dd79ba38c
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: switch.guest_mode
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.guest_mode

  - alias: Guest Mode On from Charger
    id: ce56f2a4-1c30-4890-8526-15b77e5f0ad0
    trigger:
      - platform: numeric_state
        entity_id: sensor.guest_charger_watts
        above: 0
        for: 
          seconds: 10
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: 
          - input_boolean.guest_mode
          - input_boolean.guest_phone_connected

  - alias: Guest Mode Off from Charger
    id: ec212bad-7e87-4560-82f9-148ca9020175
    trigger:
      - platform: numeric_state
        entity_id: sensor.guest_charger_watts
        below: 1
        for: 
          seconds: 10
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
      - condition: state
        entity_id: input_boolean.guest_phone_connected
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode        