# Sensors
sensor:
  #Sonoff Guest ChargerMonitor
  - platform: mqtt
    name: "Guest ChargerWatts"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Power }}"
    qos: 2
    unit_of_measurement: "W"
    icon: mdi:flash-circle
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest ChargerVoltage"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Voltage }}"
    qos: 2
    unit_of_measurement: "V"
    icon: mdi:flash-circle
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest ChargerAmps"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Current }}"
    qos: 2
    unit_of_measurement: "A"
    icon: mdi:flash-circle
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest ChargerEnergy Today"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Today }}"
    qos: 2
    unit_of_measurement: "kWh"
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest ChargerEnergy Yesterday"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Yesterday }}"
    qos: 2
    unit_of_measurement: "kWh"
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "guest-charger/tele/STATE"
    name: "Guest ChargerSignal"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "guest-charger/tele/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"