# Sensors
sensor:
  #Sonoff Guest Charger Monitor
  - platform: mqtt
    name: "Guest Charger Watts"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Power }}"
    qos: 2
    unit_of_measurement: "W"
    icon: mdi:flash-circle
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest Charger Voltage"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Voltage }}"
    qos: 2
    unit_of_measurement: "V"
    icon: mdi:flash-circle
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest Charger Amps"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Current }}"
    qos: 2
    unit_of_measurement: "A"
    icon: mdi:flash-circle
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest Charger Energy Today"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Today }}"
    qos: 2
    unit_of_measurement: "kWh"
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - platform: mqtt
    name: "Guest Charger Energy Yesterday"
    state_topic: "guest-charger/tele/SENSOR"
    value_template: "{{value_json['ENERGY'].Yesterday }}"
    qos: 2
    unit_of_measurement: "kWh"
    availability_topic: "guest-charger/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"

  - platform: mqtt
    state_topic: "guest-charger/tele/STATE"
    name: "Guest Charger Signal"
    unit_of_measurement: "%"
    value_template: "{{value_json['Wifi'].RSSI }}"
    availability_topic: "guest-charger/tele/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"

automation:
  - alias: Guest Mode On from Keypad
    id: 13ac6974-02e0-473b-84fa-f24d2d8b0bd1
    trigger:
      - platform: state
        entity_id: switch.guest_mode
        from: "off"
        to: "on"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode

  - alias: Guest Mode Off from Keypad
    id: 8fa2957d-e2a2-4ae3-b723-701f6ccf79c8
    trigger:
      - platform: state
        entity_id: switch.guest_mode
        from: "on"
        to: "off"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode

  - alias: Guest Mode Keypad On
    id: e5d6d21e-1fd1-4b11-a2c9-6135dfb039a8
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: switch.guest_mode
        state: "off"
    action:
      - service: switch.turn_on
        entity_id: switch.guest_mode

  - alias: Guest Mode Keypad Off
    id: ede11bb3-9f30-4513-864c-5ac4d413d324
    trigger:
      - platform: state
        entity_id: input_boolean.guest_mode
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: switch.guest_mode
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.guest_mode

  - alias: Guest Mode On from Charger
    id: ce56f2a4-1c30-4890-8526-15b77e5f0ad0
    trigger:
      - platform: numeric_state
        entity_id: sensor.guest_charger_watts
        above: 0
        for: 
          seconds: 10
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.guest_mode

  - alias: Guest Mode Off from Charger
    id: ec212bad-7e87-4560-82f9-148ca9020175
    trigger:
      - platform: numeric_state
        entity_id: sensor.guest_charger_watts
        below: 1
        for: 
          seconds: 10
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode        