sensor:
  - platform: template
    sensors:
      washer_status_combined:
        friendly_name: Washer Status Combined
        value_template: >-
          {% if is_state('sensor.washer', 'off') -%}
            Off
          {% elif is_state_attr('sensor.washer', 'run_state', '-') -%}
            Idle
          {% elif is_state_attr('sensor.washer', 'remain_time', '0:00') or is_state_attr('sensor.washer', 'run_state', 'Finished') -%}
            {{ (state_attr("sensor.washer", "run_state")) }}
          {% elif is_state('sensor.washer', 'on') -%}
            {{ (state_attr("sensor.washer", "run_state")) }} {{ (state_attr("sensor.washer", "remain_time")) }}
          {% else -%}
            Error
          {% endif -%}
      dryer_status_combined:
        friendly_name: Dryer Status Combined
        value_template: >-
          {% if is_state('sensor.dryer', 'off') -%}
            Off
          {% elif is_state_attr('sensor.dryer', 'run_state', '-') -%}
            Idle
          {% elif is_state_attr('sensor.dryer', 'remain_time', '0:00') or is_state_attr('sensor.dryer', 'run_state', 'Finished') -%}
            {{ (state_attr("sensor.dryer", "run_state")) }}
          {% elif is_state('sensor.dryer', 'on') -%}
            {{ (state_attr("sensor.dryer", "run_state")) }} {{ (state_attr("sensor.dryer", "remain_time")) }}
          {% else -%}
            Error
          {% endif -%}    
      washer_time_remaining:
        friendly_name: Washer Remaining Time
        value_template: "{{ state_attr('sensor.washer', 'remain_time') }}" 
      dryer_time_remaining:
        friendly_name: Dryer Remaining Time
        value_template: "{{ state_attr('sensor.dryer', 'remain_time') }}" 
