switch:
  - platform: template
    switches:
      sound_machine_master:
        unique_id: 99f4cf35-f134-4138-b09d-8af200d8f204
        friendly_name: "Master Sound Machine"
        turn_on:
          service: esphome.sound_machine_master_dfplayer_play_bedtime
        turn_off:
          service: esphome.sound_machine_master_dfplayer_stop
      sound_machine_guest:
        unique_id: 05687b2b-9bc3-4b2c-a0e0-73cce72c5285
        friendly_name: "Guest Sound Machine"
        turn_on:
          service: esphome.sound_machine_guest_dfplayer_play_bedtime
        turn_off:
          service: esphome.sound_machine_guest_dfplayer_stop

automation:
  - alias: Turn On Sound Machine
    id: 03759759-c2c7-4d9e-80c7-594b998b615a
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: disarmed
        to: armed_night
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_home
        to: armed_night
    action:
      - service: esphome.sound_machine_master_dfplayer_play_bedtime

  - alias: Turn Off Sound Machine
    id: c7b2bf10-f9f0-4ba9-9f53-21c9297ad4da
    trigger:
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_night
        to: armed_home
      - platform: state
        entity_id: alarm_control_panel.elkm1_house
        from: armed_night
        to: disarmed
    action:
      - service: esphome.sound_machine_master_dfplayer_stop      