automation:
  - alias: Vacation Mode On
    id: 367daa48-3126-4dea-bad5-89b76b6814b6
    trigger:
      - platform: template
        value_template: "{{ is_state_attr('alarm_control_panel.elkm1_house', 'armed_status', 'armed_to_vacation') }}"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode
      - service: button.press
        entity_id: button.docker_vm_frigate_away

  - alias: Notify Alarm Disarmed by Leena
    id: 47c99c56-602a-4695-9219-f8ecc9c3f0aa
    trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      to: disarmed
    condition:
      - condition: state
        entity_id: alarm_control_panel.elkm1_house
        attribute: changed_by
        state: "Leena"
    action:
      service: notify.mobile_app_hd1907
      data:
        title: Alarm Disarmed
        message: The alarm has been disarmed by Leena.

  - alias: Notify Alarm Armed in Vacation Mode
    id: 426c952b-9cfd-48d7-9dc7-eb95c2de7c20
    trigger:
    - platform: state
      entity_id: alarm_control_panel.elkm1_house
      from: arming
      to: armed_vacation
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      service: notify.mobile_app_hd1907
      data:
        title: Alarm Armed
        message: The alarm has been armed.

  - alias: Vacation Mode Off
    id: d24d2f8f-2821-41c9-90c7-042c54a223e4
    trigger:
      - platform: state
        entity_id: person.karen
        to: "home"
      - platform: state
        entity_id: person.scott
        to: "home"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode
      - service: switch.turn_off
        entity_id:
          - switch.presence_simulation
      - service: button.press
        entity_id: button.docker_vm_frigate_home

  - alias: Vacation Replay Lights Off in Morning
    id: 8757403b-1145-471c-be4d-bc48a9bbb12d
    trigger:
      - platform: state
        entity_id: input_boolean.outside_timer_lights
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: switch.turn_off
        continue_on_error: true
        entity_id:
          - switch.presence_simulation
      - service: light.turn_off
        continue_on_error: true
        entity_id:
          - light.back_porch_light
          - light.back_hall_light
          - light.front_hall_light
          - light.watch_shop_light
          - light.guest_room_light
          - light.guest_bath_light
          - light.half_bath_light
          - light.laundry_room_light
          - light.craft_room_light
          - light.master_bedroom_light
          - light.master_bathroom_lights
          - light.master_shower_light
          - light.master_toilet_light
      - service: switch.turn_off
        continue_on_error: true
        entity_id:
          - switch.back_yard_lights
          - switch.kitchen_lights
          - switch.kitchen_island_lights
          - switch.kitchen_undercabinet_lights
          - switch.dining_light
          - switch.den_lights
          - switch.foyer_lights
          - switch.drop_zone_light
      - service: script.turn_on
        entity_id: script.timer_lights_off

  - alias: Enable presence Simulation at Night
    id: dab68903-0a0c-486e-86de-c50dc31754a3
    trigger:
      - platform: state
        entity_id: input_boolean.outside_timer_lights
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: switch.turn_on
        continue_on_error: true
        entity_id:
          - switch.presence_simulation

  - alias: Trigger Timer Light Shutdown
    id: 09a08b51-bccd-45a2-9454-0b482e5b7bc3
    trigger:
      - platform: state
        entity_id: input_boolean.timer_lights_trigger
        from: "on"
        to: "off"
      #Remove next trigger once history is built for input_boolean.timer_lights_trigger.  This is a workaround for the short-term and will cause incorrect frontend indications if left on forever...
      - platform: state 
        entity_id: input_boolean.timer_lights
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
    action:
      - service: script.turn_on
        entity_id: script.timer_lights_off

input_boolean:
  vacation_mode:
    name: Vacation Mode
    icon: mdi:airplane
  timer_lights_trigger:
    name: Timer Light trigger
    icon: mdi:timer-alert

script:
  timer_lights_off:
    sequence:
      - service: switch.turn_off
        continue_on_error: true
        entity_id: 
          - switch.guest_room_lamp
          - switch.craft_room_table_lamp
          - switch.den_curio_cabinet
          - switch.master_bedroom_lamp
      - service: light.turn_off
        continue_on_error: true
        entity_id:
          - light.watch_shop_lamp
          - light.craft_room_floor_lamp
          - light.entry_lamp
          - light.den_table_lamp
          - light.dining_armoire_leds
      - service: input_boolean.turn_off
        continue_on_error: true
        data:
          entity_id: 
            - input_boolean.timer_lights
            - input_boolean.manual_timer_lights
            - input_boolean.timer_lights_trigger