sensor:
  - platform: "mqtt"
    name: "Aquara Outside Temperature"
    state_topic: "zigbee2mqtt/aquara_outside"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "°C"
    device_class: "temperature"
    value_template: "{{ value_json.temperature }}"
  - platform: "mqtt"
    name: "Aquara Outside Humidity"
    state_topic: "zigbee2mqtt/aquara_outside"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "humidity"
    value_template: "{{ value_json.humidity }}"
  - platform: "mqtt"
    name: "Aquara Outside Pressure"
    state_topic: "zigbee2mqtt/aquara_outside"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "hPa"
    device_class: "pressure"
    value_template: "{{ value_json.pressure }}"
  - platform: "mqtt"
    name: "Aquara Outside Battery"
    state_topic: "zigbee2mqtt/aquara_outside"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "%"
    device_class: "battery"
    value_template: "{{ value_json.battery }}"
  - platform: "mqtt"
    name: "Aquara Outside Link Quality"
    state_topic: "zigbee2mqtt/aquara_outside"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "-"
    value_template: "{{ value_json.linkquality }}"

